# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_resultads_waitingads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultAds',
            new_name='ResultsAds',
        ),
    ]
