# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170530_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resultsads',
            name='image',
            field=models.ImageField(help_text='Size: 600px x 200px', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='waitingads',
            name='image',
            field=models.ImageField(help_text='Size: 600px x 100px', upload_to=b''),
        ),
    ]
