# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
    ]
