# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_deductible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropType',
            new_name='Crop',
        ),
    ]
