# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawlerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='crawlerrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='acres',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='coverage',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='quarter',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='section',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='crawlerrequest',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.CrawlerResult'),
        ),
    ]
