# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20170526_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
