# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_crawlerrequest_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerrequest',
            name='result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.CrawlerResult'),
        ),
    ]
