# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20170526_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrequest',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
