# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20170530_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerresult',
            old_name='price',
            new_name='premium',
        ),
    ]
